@startmindmap

*[#F8F8FF] NLP 

**[#LightGray] Features
***_ Programação em linguagem natural
***_ Arquitetura de Fluxo de Conversa
***_ Chatbot com IA - NLP

left side

**[#LightGray] Tools
***_ Watson
***_ DialogFlow
***_ Raza 
***_ Alexa 
***_ AmazonLex

**[#LightGray]  DialogFlow 
***_ https://dialogflow.cloud.google.com/
***_ Components
****_ Agent
****_ Intents -> um categoria/label/output

@endmindmap