@startmindmap

*[#F8F8FF] Aula 2

**[#LightGray] Arquitetura/Fluxo de Conversa

***_ Sem IA
***_ Fluxo condicional
***_ Público: 
***_ Aplicação: FAQs, Suporte
***_ Landbot https://landbot.io/
***_ https://digital.blip.ai/
***_ https://www.zenvia.com/

left side


@endmindmap