@startmindmap

*[#F8F8FF] Aula 2

**[#LightGray] ChatBot sem IA

***_ Fluxo de conversa condicional
***_ Público: 
***_ Aplicação: FAQs, Suporte
***_ Usa variáveis

*** Tools:
****_ Landbot https://landbot.io/
****_ https://digital.blip.ai/
****_ https://www.zenvia.com/

*** Restrições:
****_ Sem contexto
****_ Sem integração
****_ Sem versionamento


left side

@endmindmap