@startmindmap

*[#F8F8FF] IA conversacional

**[#LightGray] Features
***_ Arquitetura de Fluxo de Conversa
***_ Chatbot com IA - NLP

left side

**[#LightGray] Tools
***_ Watson
***_ DialogFlow
***_ Raza 
***_ Alexa 
***_ AmazonLex

**[#LightGray]  DialogFlow 
***_ https://cloud.google.com/dialogflow

@endmindmap