@startmindmap

*[#F8F8FF] Fluxo de Conversa

**[#LightGray] Features
***_ Chatbot sem IA
***_ Público: 
***_ Aplicação: FAQs, Suporte
***_ Usa variáveis

left side

**[#LightGray] Tools:
***_ Landbot https://landbot.io/
***_ https://digital.blip.ai/
***_ https://www.zenvia.com/

**[#LightGray] Restrições:
***_ Sem contexto
***_ Sem integração
***_ Sem versionamento


left side

@endmindmap