@startmindmap

*[#F8F8FF] IA

**[#LightGray] Tópicos

***_ Estratégia de canais
****_ Onde seu público está? 
****_ Teams, Whatsapp, Web

**[#LightGray] Oportunidades

***_ Medicina -> Processos, Triagem
***_ Validações -> CPF, Data
***_ Área Fiscal
***_ Celebridades
***_ FAQ em Chatbot
***_ Automação residencial

**[#LightGray] Avatar animado -> 
***_ Público construindo o produto
***_ Humanização do avatar -> Engajamento
***_ Canais -> tecnologia, segmentação, segurança, alcance, custo

left side

**[#LightGray] Estudar
***_ Design Thinking
***_ UX

**[#LightGray] Tools

***_ fobi.io
***_ DialogFlow
***_ NodeRed
***_ OpenAI

**[#LightGray] Pessoas

***_ Suzan Carolina Monteiro (Rei do Pitaco)

@endmindmap